// Generated by ReScript, PLEASE EDIT WITH CARE


var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var count = {
  contents: 0
};

function renderCountView(n) {
  var el = document.getElementById("count");
  el.innerText = "Count is " + n;
  if (n > 0) {
    el.className = "count count-positive";
  } else if (n < 0) {
    el.className = "count count-negative";
  } else {
    el.className = "count count-zero";
  }
  
}

function updateCount(steps) {
  count.contents = count.contents + steps | 0;
  
}

function renderView(steps) {
  updateCount(steps);
  return renderCountView(count.contents);
}

function plusOne(param) {
  return renderView(1);
}

function minusOne(param) {
  return renderView(-1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  count ,
  renderCountView ,
  updateCount ,
  renderView ,
  plusOne ,
  minusOne ,
  
}
/* plusButton Not a pure module */
